rproxy:
  image: jwilder/nginx-proxy
  ports:
    - "80:80"
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro
  links:
    - web

web:
  extends:
    file: common.yml
    service: web
  volumes:
    - .:/code
  links:
    - redis
    - mongo
  environment:
    - REDIS_HOST=redis
    - VIRTUAL_HOST=learn.compose.com

redis:
  image: redis

mongo:
  image: mongo
  ports:
    - "27071:27017"

hub:
  image: selenium/hub
  ports:
    - "4444:4444"

firefox:
  image: selenium/node-firefox
  links:
    - hub

chrome:
  image: selenium/node-chrome
  links:
    - hub

# dev/test services

test:
  build: .
  dockerfile: DockerfileTest.docker
  volumes:
    - .:/code
  environment:
    - REDIS_HOST=redis
  entrypoint: ["make"]
  command: ["test"]
  links:
    - redis
    - mongo
    - hub
    - firefox


pycharm:
  build: .
  dockerfile: DockerfileDeveloper.docker
  working_dir: /home/developer/projects/pastelike 
  tty: true
  entrypoint: ["/home/developer/bin/pycharm.sh"]
  command: ["/home/developer/projects/pastelike"]
  environment:
    - DISPLAY
    - REDIS_HOST=redis
  volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix
    - /etc/localtime:/etc/localtime:ro
    - ~:/home/developer
  links:
    - redis
    - mongo
    - hub
    - firefox

